name: Affected Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  affected:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: latest
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      run: pnpm install

    - name: Test Affected Projects
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      run: pnpm nx affected -t test --base=main --head=HEAD
    
    - name: Test Affected Projects Last Commit
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: pnpm nx affected -t test --base=main~1 --head=HEAD
